[package]
name = "protobuf_macros"
version = "0.2.0"
authors = ["Paul Liétar <paul@lietar.net>"]

[lib]
name = "protobuf_macros"
path = "src/lib.rs"
plugin = true
test = false

[dependencies.aster]
version = "^0.13.1"
