[package]
name = "protobuf_macros"
version = "0.3.0"
authors = ["Paul Liétar <paul@lietar.net>"]

[lib]
name = "protobuf_macros"
path = "src/lib.rs"
plugin = true
test = false
crate-type = ["dylib", "rlib"]

[dependencies]
aster = "^0.13.1"
syntex = { version = "*", optional = true }
syntex_syntax = { version = "*", optional = true }

[features]
with-syntex = ["syntex", "syntex_syntax", "aster/with-syntex"]
