[package]
name = "protobuf_macros_sample"
version = "0.1.0"
authors = ["Paul Liétar <paul@lietar.net>"]

[[bin]]
name = "sample"
path = "main.rs"

[dependencies.protobuf]
git = "https://github.com/stepancheg/rust-protobuf.git"

[dependencies.protobuf_macros]
path = ".."
